[package]
name = "focus"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
anyhow = "1.0.100"
reqwest = "0.12.23"
serde = "1.0.228"
serde_json = "1.0.145"
serde_yaml = "0.9.34"
